Update to version 0.9.0
conda-forge/px-proxy-feedstock pull request #18
Opened 2024-01-28 10:34 UTC by m-rossi

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Not sure why it does not trigger the PR automatically.

Some notes:
* I did not include https://github.com/genotrance/px/blob/v0.9.0/setup.py#L82 as we onyl build for Python > 3.8

2024-01-28 10:35 UTC, m-rossi commented
@conda-forge-admin, please rerender

2024-01-28 10:59 UTC, m-rossi commented
@conda-forge-admin, please rerender

2024-01-28 11:17 UTC, m-rossi commented
Looks good. I also enabled builds on Linux with success.

2024-01-29 09:31 UTC, fcollonval requested changes
Thanks a lot @m-rossi 

I have a minor suggestion. And we should be good to go.

2024-01-29 09:31 UTC, fcollonval commented on recipe/meta.yaml
>      - python
let's make the python constraint explicit

```suggestion
    - python >=3.8.0
```

2024-01-29 09:37 UTC, fcollonval commented
Ok let's revert my suggestion as the linter does not like it.

2024-01-29 09:37 UTC, fcollonval commented on recipe/meta.yaml
> +    - python >=3.8.0
```suggestion
    - python
```

2024-01-29 10:14 UTC, merged